export const FETCH_BUCKETS_START = "FETCH_BUCKETS_START";
export const FETCH_BUCKETS_SUCCESS = "FETCH_BUCKETS_SUCCESS";
export const FETCH_BUCKETS_FAILURE = "FETCH_BUCKETS_FAILURE";
export const CREATE_BUCKET_START = "CREATE_BUCKET_START";
export const CREATE_BUCKET_SUCCESS = "CREATE_BUCKET_SUCCESS";
export const CREATE_BUCKET_FAILURE = "CREATE_BUCKET_FAILURE";
export const OPEN_NEW_BUCKET_FORM = "OPEN_NEW_BUCKET_FORM";
export const CLOSE_NEW_BUCKET_FORM = "CLOSE_NEW_BUCKET_FORM";
